---
- name: Install Junos OS - Not Enough Space error
  hosts: Junos_all
  roles:
    - Juniper.junos 
  connection: local
  gather_facts: no
  
  vars:
    netconf_port: 830
    wait_time: 3600
    OS_version: 20.2R1-S2.1
    OS_package: junos-arm-32-20.2R1-S2.1.tgz
    pkg_dir: /var/lib/awx/custom-venv/junos/Firmware
    netconf_port: 830
    install_timeout: 2000
    checksum_timeout: 420

  tasks:

    - name: Install OS package
      juniper_junos_software:
       local_package: "/var/lib/awx/custom-venv/junos/Firmware/os-package.tgz"
       force_host: yes
       reboot: no
    
    - name: Install Hooks
      juniper_junos_software:
        local_package: "/var/lib/awx/custom-venv/junos/Firmware/package-hooks-ex.tgz"
        force_host: yes
        reboot: no
        
    - name: Install Junos OS package
      juniper_junos_software:
        version: "{{ OS_version }}"
        local_package: "{{ pkg_dir }}/{{ OS_package }}"
        kwargs: {"no-copy": true,"force": true,"unlink": true}
#        reboot: yes
        force_host: yes
      register: sw
      notify:
#      - wait_reboot   
      
    - name: reboot
      junos_command:
        commands: request system reboot
