---
- name: Install Junos OS - Not Enough Space error
  hosts: Junos_all
  roles:
    - Juniper.junos 
  connection: local
  gather_facts: no
  
  vars:
    netconf_port: 830
    wait_time: 3600

  tasks:

    - name: Install OS package
      juniper_junos_software:
       local_package: "/var/lib/awx/custom-venv/junos/Firmware/os-package.tgz"
       force_host: yes
       reboot: no
    
    - name: Install Hooks
      juniper_junos_software:
        local_package: "/var/lib/awx/custom-venv/junos/Firmware/package-hooks-ex.tgz"
        force_host: yes
        reboot: no
    
