---
- name: Install Junos OS - EX3400
  hosts: Junos_Test
  roles:
    - Juniper.junos 
  connection: netconf
  gather_facts: no
  
  vars:
    OS_version: "20.2R1-S2.1"
    OS_package: "junos-arm-32-20.2R1-S2.1.tgz"
    pkg_dir: "/var/lib/awx/custom-venv/junos/Firmware"
    netconf_port: 830
    wait_time: 3600

  tasks:
    - name: Checking NETCONF connectivity
      wait_for: 
        host: "{{ ansible_host }}" 
        port: "{{ netconf_port }}"
        timeout: 5

    - name: Install Junos OS package
      juniper_junos_software:
        version: "{{ OS_version }}"
        kwargs:
          unlink: true
        no_copy: true
        local_package: "{{ pkg_dir }}/{{ OS_package }}"
        reboot: true
        
        validate: no
        force_host: yes
      register: sw
      notify:
      - wait_reboot

    - name: Print response
      debug:
        var: response

  handlers:
    - name: wait_reboot
      wait_for: 
        host: "{{ inventory_hostname }}"
        port: "{{ netconf_port }}"
        timeout: "{{ wait_time }}"
      when: not sw.check_mode
