---
- name: Junos Firmware Install 
  hosts: Junos_all
  connection: local
  gather_facts: no
  roles:
    - Juniper.junos
    
  vars:
    install_timeout: 2000
    checksum_timeout: 420

  tasks:
   - name: Install OS package
     juniper_junos_software:
       local_package: "/var/lib/awx/custom-venv/junos/Firmware/os-package.tgz"
       force_host: yes
       reboot: no
       
   - name: Install Hooks
     juniper_junos_software:
        local_package: "/var/lib/awx/custom-venv/junos/Firmware/package-hooks-ex.tgz"
        force_host: yes
        reboot: no

   - name: Install Junos OS package
     juniper_junos_software:
        version: "20.2R1-S2.1"
        local_package: "/var/lib/awx/custom-venv/junos/Firmware/junos-arm-32-20.2R1-S2.1.tgz"
        kwargs: 
          unlink: true
        nssu: yes
        force_host: yes
        reboot: yes
