---
- name: Install Junos OS - EX4600
  hosts: Junos_all
  roles:
    - Juniper.junos 
  connection: local
  gather_facts: no
  
  vars:
    OS_version: "20.2R1-S2.1"
    OS_package: "junos-arm-32-20.2R1-S2.1.tgz"
    pkg_dir: "/var/lib/awx/custom-venv/junos/Firmware"
    netconf_port: 830

  tasks:
    - name: Checking NETCONF connectivity
      wait_for: 
        host: "{{ ansible_host }}" 
        port: "{{ netconf_port }}"
        timeout: 65

    - name: Install Junos OS package
      juniper_junos_software:
        version: "{{ OS_version }}"
        local_package: "{{ pkg_dir }}/{{ OS_package }}"
        force_host: yes
        kwargs:
          unlink: yes
        reboot: yes
        #nssu: yes
        install_timeout: 2000
        checksum_timeout: 420
