---
- name: Install Junos OS - EX4600
  hosts: Junos_Test
  roles:
    - Juniper.junos 
  connection: local
  gather_facts: no
  
  vars:
    OS_version: "19.1R3-S4.6"
    OS_package: "jinstall-host-ex-4600-19.1R3-S4.6-signed.tgz"
    pkg_dir: "/var/lib/awx/custom-venv/junos/Firmware"
    netconf_port: 830
    wait_time: 3600
    install_timeout: 2000
    checksum_timeout: 420

  tasks:

    - name: Install Junos OS package
      juniper_junos_software:
        version: "{{ OS_version }}"
        local_package: "{{ pkg_dir }}/{{ OS_package }}"
        force_host: yes
        kwargs:
          unlink: yes
        reboot: yes
        validate: no
      register: sw
      notify:
      - wait_reboot

  handlers:
    - name: wait_reboot
      wait_for: 
        host: "{{ ansible_host }}"
        port: "{{ netconf_port }}"
        timeout: "{{ wait_time }}"
      when: not sw.check_mode
