---
- name: Junos Firmware Install 
  hosts: Junos_all
  connection: local
  gather_facts: no
  roles:
    - Juniper.junos

  ##This installs os-package that helps with the lack of storage space in tmp folder on ex3400##
  tasks:
   - name: Install OS package
     juniper_junos_software:
       local_package: /var/lib/awx/custom-venv/junos/Firmware/os-package.tgz
       install_timeout: 2000
       checksum_timeout: 420
       force_host: yes
       reboot: no

  ## This installs package-hooks that help with the lack of storage space in tmp folder on ex3400 ##
   - name: Install Hooks
     juniper_junos_software:
        local_package: /var/lib/awx/custom-venv/junos/Firmware/package-hooks-ex.tgz
        install_timeout: 2000
        checksum_timeout: 420
        force_host: yes
        reboot: no

   ## This installs the Junos firmware ##
   ## nssu option is used only with a preprovisioned virtual chassis ##
   - name: Install Junos OS package
     juniper_junos_software:
        version: 20.2R1-S2.1
        local_package: /var/lib/awx/custom-venv/junos/Firmware/junos-arm-32-20.2R1-S2.1.tgz
        kwargs: 
          unlink: yes
          reboot: yes
        force_host: yes
        reboot: true
        #nssu: yes 
        install_timeout: 3000
        checksum_timeout: 420
