---
- name: Install Junos OS - Not Enough Space error
  hosts: Junos_all
  roles:
    - Juniper.junos 
  connection: local
  gather_facts: no
  
  vars:
    netconf_port: 830
    wait_time: 3600
    

  tasks:

    - name: Install OS package
      juniper_junos_software:
       local_package: "/var/lib/awx/custom-venv/junos/Firmware/os-package.tgz"
       reboot: no
    
    - name: Install Hooks
      juniper_junos_software:
        local_package: "/var/lib/awx/custom-venv/junos/Firmware/package-hooks-ex.tgz"
        reboot: no
    
    - name: Install Junos OS package
      juniper_junos_software:
        version: "{{ version }}"
        local_package: "/var/lib/awx/custom-venv/junos/Firmware/{{ package }}"
        kwargs:
          unlink: yes
        reboot: yes
        install_timeout: 2000
        checksum_timeout: 420
      register: sw
      notify:
      - wait_reboot

  handlers:
    - name: wait_reboot
      wait_for: 
        host: "{{ ansible_host }}"
        port: "{{ netconf_port }}"
        timeout: "{{ wait_time }}"
      when: not sw.check_mode
