---
- name: Install Junos OS - EX3400
  hosts: Junos_Test
  roles:
    - Juniper.junos 
  connection: local
  gather_facts: no
  
  vars:
    OS_version: 18.1R3-S3.8
    OS_package: junos-arm-32-18.1R3-S3.8.tgz
    pkg_dir: /var/lib/awx/custom-venv/junos/Firmware
    netconf_port: 830
    wait_time: 3600
    install_timeout: 2000
    checksum_timeout: 420

  tasks:

    - name: Install Junos OS package
      juniper_junos_software:
        version: "{{ OS_version }}"
        local_package: "{{ pkg_dir }}/{{ OS_package }}"
        kwargs: {"force": true,"unlink": true}
        reboot: yes
      register: sw
      notify:
      - wait_reboot

  handlers:
    - name: wait_reboot
      wait_for: 
        host: "{{ ansible_host }}"
        port: "{{ netconf_port }}"
        timeout: "{{ wait_time }}"
      when: not sw.check_mode
