---
- name: Install Junos OS - EX4600
  hosts: Junos_Test
  roles:
    - Juniper.junos 
  connection: local
  gather_facts: no
  
  vars:
    OS_version: "20.2R1-S2.1"
    OS_package: "jinstall-host-ex-4600-20.2R1-S2.1-signed.tgz"
    pkg_dir: "/tftproot"
    netconf_port: 830
    wait_time: 3600

  tasks:
    - name: Checking NETCONF connectivity
      wait_for: 
        host: "{{ ansible_host }}" 
        port: "{{ netconf_port }}"
        timeout: 5

    - name: Install Junos OS package
      juniper_junos_software:
        version: "{{ OS_version }}"
        local_package: "{{ pkg_dir }}/{{ OS_package }}"
        reboot: true
        validate: no
      register: sw
      notify:
      - wait_reboot

    - name: Print response
      debug:
        var: response

  handlers:
    - name: wait_reboot
      wait_for: 
        host: "{{ ansible_host }}"
        port: "{{ netconf_port }}"
        timeout: "{{ wait_time }}"
      when: not sw.check_mode
