---
- name: Test
  hosts: Junos_Test
  roles:
    - Juniper.junos 
  connection: local
  gather_facts: no
  
  
  tasks: 
   - name: Delete JUNOS L3 logical interface
     junipernetworks.junos.junos_l3_interfaces:
        config:
        - name: interface-range XIRRUS-WAP
     state: show
