  
- name: Clear storage space
  hosts: Junos_all
  gather_facts: no

  vars:
    ansible_connection: netconf
    ansible_command_timeout: 60


  tasks: 
    - name: System storage cleanup
      junos_command:
        commands: request system storage cleanup all-members no-confirm
