---
- name: cli command
  hosts: Junos_all
  gather_facts: no

  vars: 
    ansible_connection: network_cli

  tasks:
    - name: show command
      cli_command:
        command: 
            - "show interface terse"
   #         - "set interfaces {{ irb }} family inet address {{ IP }}"







# show ethernet-switching table | match {{MAC}}
