---
- name: cli command
  hosts: Junos_all
  gather_facts: no

  vars: 
    ansible_connection: network_cli

  tasks:
    - name: show command
      cli_command:
        command:
            - set interfaces ae1 unit 0 family ethernet-switching interface mode trunk       
            - set interfaces ae1 unit 0 family ethernet-switching vlan members all







# show ethernet-switching table | match {{MAC}}
