---
- name: cli command
  hosts: Junos_all
  gather_facts: no

  vars: 
    ansible_connection: network_cli

  tasks:
    - name: set command
      cli_command:
        command:
            -  show version







# show ethernet-switching table | match {{MAC}}
