---
- name: LAG
  hosts: Junos_all
  roles:
    - Juniper.junos 
  connection: local
  gather_facts: no
  
  tasks: 
   - name: load configure lines into device
     junos_config:
       lines: 
        - "replace pattern Test with test12 | match {{ irb }}"






# show ethernet-switching table | match {{MAC}}
