---
- name: cli command
  hosts: Junos_all
  gather_facts: no

  vars: 
    ansible_connection: network_cli

  tasks:
    - name: show command
      cli_command:
        command: "set interfaces et-0/0/24 ether-options 802.3ad ae1"

    - name: show command
      cli_command:
        command: 
        - "show chassis hardware"




# show ethernet-switching table | match {{MAC}}
