---
- name: cli command
  hosts: Junos_all
  gather_facts: no

  vars: 
    ansible_connection: network_cli

  tasks:
    - name: set command
      cli_command:
        command:
            - 'set interfaces interface-range XIRRUS-WAP unit 0 family ethernet-switching vlan members Johnson_Controls'







# show ethernet-switching table | match {{MAC}}
