---
- name: Not Enough Space Error
  hosts: Junos_all
  connection: local
  gather_facts: no
  roles:
    - Juniper.junos

  tasks: 
   - name: Copy OS Package
     junos_scp:
      src: /var/lib/awx/custom-venv/junos/Firmware/os-package.tgz
      dest: var/tmp/

   - name: Copy Hooks
     junos_scp:
     src: /var/lib/awx/custom-venv/junos/Firmware/package-hooks-ex.tgz
     dest: var/tmp/


   - name: Copy Junos OS
     junos_scp:
     src: /var/lib/awx/custom-venv/junos/Firmware/junos-arm-32-20.2R1-S2.1.tgz
     dest: var/tmp/

  
   - name: adding os-package
     junos_command:
      commands: "request system software add /var/tmp/os-package.tgz"
      reboot: no 

   - name: adding hooks
     junos_command:
      commands: "request system software add /var/tmp/package-hooks-ex.tgz"
      reboot: no

   - name: Installing Junos OS
     junos_command:
      commands: "request system software add /var/tmp/junos-arm-32-20.2R1-S2.1.tgz force unlink no-copy"
      reboot: yes
