---
- name: Not Enough Space Error
  hosts: Junos_all
  gather_facts: no
  roles:
    - Juniper.junos
    
  vars:
    ansible_connection: netconf
  

  tasks: 
   - name: Copy OS Package
     junos_scp:
      host: "{{ ansible_host }}"
      src: /var/lib/awx/custom-venv/junos/Firmware/os-package.tgz
      dest: var/tmp/
      
 
