---
- name: Get device facts and configuration
  hosts: Junos_all
  roles:
    - Juniper.junos
  connection: local
  gather_facts: no

  tasks:
    - name: Retrieve device facts and configuration and save facts to file
      juniper_junos_facts:        
        savedir: "/var/lib/awx/custom-venv/junos/configs"
        config_format: "text"
      register: result

    - name: Print configuration
      debug:
        var: result.ansible_facts.junos.config
