---
- name: Collect default set of facts
  hosts: Junos_all
  gather_facts: no

  tasks:
    - name: Collect default set of facts and configuration
      junos_facts:
        gather_subset: config
         register: junos
    
    - name: Print some facts
      debug:
        msg: "device {{ junos.ansible_facts.ansible_net_hostname }} is a {{ junos.ansible_facts.ansible_net_model }} running junos version {{ junos.ansible_facts.ansible_net_version }}"
