---
- name: create configuration_backup directories
  hosts: AnsibleTest
  gather_facts: no
  connection: local
  tasks:

   - name: create configuration directory
     file:
       path: "/var/lib/awx/projects/configuration/Junos"
       state: directory


   - name: create configuration subdirectories
     file:
       path: "/var/lib/awx/projects/configuration/Junos"
       state: directory
       with_items:
       - text

