---
- name: Collect default set of facts
  hosts: Junos_all
  gather_facts: no

  vars:
    ansible_command_timeout: 60
    ansible_connection: netconf
    connection_settings:
      host: "{{ ansible_host }}"
      port: 22
      timeout: 180

  tasks:
    - name: Collect default set of facts and configuration
      junos_facts:
        gather_subset: config
       register: junos
    
    - name: Print some facts
      debug:
        msg: "device {{ junos.ansible_facts.ansible_net_hostname }} is a {{ junos.ansible_facts.ansible_net_model }} running junos version {{ junos.ansible_facts.ansible_net_version }}"
