- name: Gather facts from Junos devices
  hosts: Junos_all
  connection: local
  gather_facts: no
  roles:
    - Juniper.junos
  tasks:
    - name: Gather Junos facts with no configuration
      junos_facts:
