---
- name: Get device facts
  hosts: Junos_all
  roles:
    - Juniper.junos
  connection: local
  gather_facts: no

  tasks:
    - name: Retrieve device facts and save to file
      juniper_junos_facts:        
        savedir: "{{ playbook_dir }}"
