---
 - name: Retrieve configuration from Junos devices
   hosts: Junos_all
   roles:
    - Juniper.junos
   connection: local
   gather_facts: no
   tasks:
   - name: Retrieve configuration from Junos devices
     junos_get_config:
      dest: "/home/.ansible/playboks/configs/Hudnall.conf"
      format: text
      logfile: "/home/.ansible/playboks/configs/junos_get_config.log"
      filter: system
