---
- name: Examples of juniper_junos_software
  hosts: Junos_Test
  connection: local
  gather_facts: no

  tasks:
    - name: Execute a basic Junos software upgrade.
      juniper_junos_software:
        local_package: "./tftproot/junos-arm-32-20.2R1-S2.1.tgz"
      register: response
    - name: Print the complete response.
      debug:
        var: response


