---
- name: Test
  hosts: Junos_Test
  roles:
    - Juniper.junos 
  connection: local
  gather_facts: no


  tasks:   
   - name: Retrieve Junos OS version
     junos_command:
      commands: show interface interface-range XIRRUS-WAP
