---
- name: Interface-Range
  hosts: Junos_Test
  roles:
    - Juniper.junos 
  connection: local
  gather_facts: no

         
  tasks: 
    - name: Interface
      junos_command:
          commands:
          - "show configuration interfaces interface-range {{ range | mandatory }}"
        
      register: dirtyinterface
        

       
