---
- name: Test
  hosts: Junos_Test
  roles:
    - Juniper.junos 
  connection: local
  gather_facts: no
      

  tasks:   
   - name: Interface Range
     junos_config:
      lines:
        - show configuration interfaces interface-range XIRRUS-WAP | match "member ge-*"
         
 
         
