---
- name: Test
  hosts: Junos_Test
  roles:
    - Juniper.junos 
  connection: local
  gather_facts: no
      

  tasks:   
   - name: run multiple commands on remote nodes
     junos_command:
        commands:
         - show interfaces interface-range XIRRUS-WAP
