---
- name: Test
  hosts: Junos_Test
  roles:
    - Juniper.junos 
  connection: local
  gather_facts: no

  vars: 
      range: "{{ XIRRUS-WAP }}" 
      

  tasks:   
   - name: run multiple commands on remote nodes
     junipernetworks.junos.junos_command:
        commands:
         - show interfaces interface-range {{ range }}
