---
- name: Interface-Range
  hosts: Junos_Test
  roles:
    - Juniper.junos 
  connection: local
  gather_facts: no

         
  tasks: 
    - name: Interface
      junos_command:
        commands: show configuration interfaces interface-range XIRRUS-WAP | match "member ge-*"
        register: dirtyinterface
        
    - name: Parse through and remove "member"
      debug:
        var: dirtyInterfaces
