---
- name: Test
  hosts: Junos_Test
  roles:
    - Juniper.junos 
  connection: local
  gather_facts: no


  tasks:   
   - name: load configure lines into device
     junos_command:
       commands: show interfaces interface-range XIRRUS-WAP
