---
- name: Test
  hosts: Junos_Test
  roles:
    - Juniper.junos 
  connection: local
  gather_facts: yes


  tasks:   
   - name: load configure lines into device
     junos_command:
       command:
        - show interfaces interface-range XIRRUS-WAP
