---
- name: Test
  hosts: Junos_Test
  roles:
    - Juniper.junos 
  connection: local
  gather_facts: no


  tasks:   
   - name: load configure lines into device
     junos_config:
       lines:
        - show interface interface-range XIRRUS-WAP
