---
- name: Get Interfaces in Interface Ranges
  hosts: Junos_Test
  gather_facts: no
  roles:
    - Juniper.junos
  tasks:
    - name: Get Interfaces in Interface Ranges from config
      junos_config:
        lines:
         - show configuration interfaces interface-range XIRRUS-WAP | match member ge-*
      register: dirtyInterfaces
    - name: print dirtyInterfaces.stdout_lines
      debug:
        var: dirtyInterfaces.stdout_lines


