---
- name: JunosVlan
  hosts: Junos_all
  roles:
    - Juniper.junos 
  connection: local
  gather_facts: no
   
  tasks: 
        
    - name: configure VLAN ID and name
      junos_vlan:
        name: Johnson_Controls
        vlan_id: 142
        
