---
- name: Firmware
  hosts: Junos_Test
  gather_facts: no
  connection: netconf


  tasks:
    - name: upgrade firmware
      junos_package:
        src: junos-arm-32-20.2R1-S2.1.tgz
        version: 20.2R1-S2.1
