---
- name: Install Junos OS
  hosts: Junos_Test
  roles:
    - Juniper.junos 
  connection: local
  gather_facts: no

 vars:
    OS_version: "20.2R1-S2.1"
    OS_package: "junos-arm-32-20.2R1-S2.1.tgz"
    pkg_dir: "/home/tftproot"
    #log_dir: "/var/log/ansible"
    netconf_port: 830
    wait_time: 3600

tasks:
    - name: Checking NETCONF connectivity
      wait_for: 
        host: "{{ inventory_hostname }}" 
        port: "{{ netconf_port }}"
        timeout: 5


- name: Install Junos OS package
      juniper_junos_software:
        version: "{{ OS_version }}"
        local_package: "{{ pkg_dir }}/{{ OS_package }}"
        reboot: true
        validate: true
       # logfile: "{{ log_dir }}/software.log"
      register: sw
      notify:
      - wait_reboot

 - name: Print response
      debug:
        var: sw

  handlers:
    - name: wait_reboot
      wait_for: 
        host: "{{ inventory_hostname }}"
        port: "{{ netconf_port }}"
        timeout: "{{ wait_time }}"
      when: not sw.check_mode
