---
- name: Install Junos OS - EX3400
  hosts: Junos_all
  roles:
    - Juniper.junos 
  connection: local
  gather_facts: no
  

  tasks:

  - name: install local package on remote device
    junipernetworks.junos.junos_package:
      src: junos-vsrx-12.1X46-D10.2-domestic.tgz
      timeout: 1200
      reboot: yes
      force_host: yes
      register: sw
      notify:
      - wait_reboot

  handlers:
    - name: wait_reboot
      wait_for: 
        host: "{{ ansible_host }}"
        port: "{{ netconf_port }}"
        timeout: "{{ wait_time }}"
      when: not sw.check_mode
