---
- name: upgrade junos
  hosts: Junos_all
  connection: local
  gather_facts: no

  tasks:
  - name: install local package on remote device and reboot the device
    junos_package:
      src: "/var/lib/awx/custom-venv/junos/Firmware/junos-arm-32-20.2R1-S2.1.tgz"
      reboot: true
      provider: "{{ credentials }}"
      version: 20.2R1-S2.1
