---
- name: Install Junos OS
  hosts: Junos_Test
  roles: 
    - Juniper.junos
  connection: local
  gather_facts: no

  vars:
    ansible_connection: netconf
    ansible_python_interpreter: "{{ '/usr/bin/env python-docker' }}"
    ansible_command_timeout: 60
 

  tasks:

  - name: upgrade
    junos_install_os:
     junos_install_os:
      host={{ junos_host }}
      user={{ ADMUSER }}
      passwd={{ ADMPASS }}
      version=12.3R12.4
      package={{playbook_dir}}/jinstall-junos-arm-32-20.2R1-S2.1.tgz
      logfile=software.log
      port=830
      reboot=yes
      no_copy=no
     
