  ---
- name: Install Junos OS - EX3400
  hosts: Junos_all
  roles:
    - Juniper.junos 
  connection: local
  gather_facts: no
  

  tasks:

  - name: install local package on remote device
    junipernetworks.junos.junos_package:
      src: /var/lib/awx/custom-venv/junos/Firmware/junos-arm-32-20.2R1-S2.1.tgz
      timeout: 1200
      reboot: yes
      force_host: yes
