
---
- name: Install Junos OS
  hosts: Junos_Test
  roles: 
    - Junper.junos
  connection: local
  gather_facts: no

  vars:
    ansible_connection: netconf
    ansible_python_interpreter: "{{ '/usr/bin/env python-docker' }}"
    ansible_command_timeout: 60
    OS_version: "20.2R1-S2.1"
    OS_package: "/tftproot/junos-arm-32-20.2R1-S2.1.tgz"
    pkg_dir: "software"
    log_dir: "/var/log/ansible"
    netconf_port: 830
    wait_time: 3600


  tasks:

    - set_fact:
      ansible_python_interpreter: '{{ ansible_playbook_python }}'
      delegate_to: localhost    
      delegate_facts: true

    - name: Checking NETCONF connectivity
      wait_for:
         host: "{{ inventory_hostname }}"
         port: "{{ netconf_port }}"
         timeout: 5
        
    - name: Install Junos OS package
      juniper_junos_software:
        version: "{{ OS_version }}"
        local_package: "{{ pkg_dir }}/{{ OS_package }}"
        reboot: true
        validate: true
        logfile: "{{ log_dir }}/software.log"
        register: sw
        notify:
        - wait_reboot

    - name: Print response
      debug:
        var: sw
