---
- name: Install Junos OS
  hosts: Junos_all
  roles:
    - junipernetworks.junos 
  connection: netconf
  gather_facts: no

- name: install local package on remote device 
  junipernetworks.junos.junos_package:
    src: tftproot/junos-arm-32-20.2R1-S2.1.tgz
    force_host: yes
    reboot: yes
