---
- name: Examples of juniper_junos_software
  hosts: Junos_Test
  connection: local
  gather_facts: no
  roles:
    - Juniper.junos
Tasks:    
- name: install local package on remote device
  junos_package:
    src: junos-arm-32-20.2R1-S2.1.tgz
