---
- name: upgrade junos
  hosts: AnsibleTest
  connection: local
  gather_facts: no
    

- name: install local package on remote device and reboot the device
  junipernetworks.junos.junos_package:
      src: "{{playbook_dir}}/jinstall-junos-arm-32-20.2R1-S2.1.tgz"
      reboot: true
      version: 20.2R1-S2.1
