---
- name: Clear storage space
  hosts: Junos_all
  roles:
     - Juniper.junos
  gather_facts: no
  connection: local




  tasks: 
    - name: Search Mac 
      junos_command:
         commands: sh -c "cli show ethernet-switching table \| match 00:10:8d"
