---
- name: Clear storage space
  hosts: Junos_all
  roles:
     - Juniper.junos
  gather_facts: no
  connection: local




  tasks: 
    - name: Search Mac 
      junos_command:
         commands: show ethernet-switching table 
         wait_for: result[0] contains 00:10:8d
         display: text
