---
- name: Finding MAC address
  hosts: Junos_all
  roles:
     - Juniper.junos
  gather_facts: no
  connection: local




  tasks: 
    - name: Search Mac 
      junos_command:
         commands: "show ethernet-switching table | match 00:10:8d"
         display: json
      register: MAC
      
    - name: query
      debug: msg="{{ MAC.json | json_query(jmesquery) }}"
      vars:
        jmesquery: "[*].{Number: 00:10:8d}"
