---
- name: Test
  hosts: Junos_all
  roles:
    - Juniper.junos 
  connection: netconf
  gather_facts: no
  
  
  tasks: 
   - name: Mac
     junos_command:
      commands:
        - sh -c "cli show ethernet-switching table \| match 00:10:8d"
