---
- name: Test
  hosts: Junos_all
  roles:
    - Juniper.junos 
  connection: local
  gather_facts: yes
  

  tasks:
  - name: Collect only facts
    setup:
      filter: ansible_mac_address
    register: response
  - name: "Print result"
    debug:
        var: response
        

