---
- name: Test
  hosts: Junos_all
  roles:
    - Juniper.junos 
  connection: local
  gather_facts: no
  
  
  tasks: 
   - name: Mac
     junos_command:
      commands:
        - show version
        - show interfaces
      wait_for:
        - result[0] contains Juniper
        - result[1] contains Loopback0
