---
- name: Test
  hosts: Junos_Test
  roles:
    - Juniper.junos 
  connection: local
  gather_facts: no
  
  
  tasks: 
    - name: run multiple commands and evaluate the output
      junos_command:
      commands:
        - show version
        - show interfaces
      wait_for:
        - result[0] contains Juniper
        - result[1] contains Loopback0
