---
- name: Test
  hosts: Junos_all
  roles:
    - Juniper.junos 
  connection: local
  gather_facts: no
  

  tasks:
   - name: junos cli
     junos_cli:
       cli: "show ethernet-switching table | match 00:10:8D"
        

