---
- name: Test
  hosts: Junos_all
  roles:
    - Juniper.junos 
  connection: local
  gather_facts: no
  
  tasks:
    - name: Get Arp info
      juniper_junos_table:        
        file: "arp.yml"
      register: result
      
    - name: Print response
      debug:
        var: result
        
        
    - name: Print Response
      debug:
        msg: "{{ result | json_query(query) }}"
      vars:
        query: "resource[?mac_address=='{{ 00-10-8D-01-83-96 }}']"

