---
- name: Test
  hosts: Junos_all
  roles:
    - Juniper.junos 
  connection: local
  gather_facts: no
  
  tasks:
    - name: Get Arp info
      juniper_junos_table:        
        file: "arp.yml"
        kwargs: 
          interface_name: "ge-1/0/0"
      register: result
      
    - name: Print response
      debug:
        var: result
        
