---
- name: Clear storage space
  hosts: Junos_all
  roles:
     - Juniper.junos
  gather_facts: no
  connection: local




  tasks: 
   - name: Retrieve mac-address
      juniper_junos_table:
        file: "mactable.yml"
        table: "mactable"
        kwargs:
          match: "00:10:8d"
      register: response
  - name: Print response
      debug:
        var: response
