---
- name: Test
  hosts: Junos_all
  roles:
    - Juniper.junos 
  connection: local
  gather_facts: no
  

  tasks:

  - name: Find NICs MAC
    ansible.builtin.debug:
      msg: " interface {{ ansible_interfaces }}'s MAC is {{ ansible_facts[item]['00:10:8D:']|default(None) }}"
    with_items:
    - "{{ ansible_interfaces }}"

