---
- name: Test
  hosts: Junos_all
  roles:
    - Juniper.junos 
  connection: local
  gather_facts: no
  
  
  tasks: 
   - name: Mac
     junos_command:
      commands:
        - show ethernet-switching table brief
        - show version
        
      wait_for:
        - result[0] contains "00:10:8d"
        - result[1] contains 20
