---
- name: Create User
  hosts: Junos_all
  roles:       
    - Juniper.junos
  connection: local
  gather_facts: no
   

  tasks:
    - name: create new user account
      junos_user:
        name: fortinac
        state: present
        
    - name: set user password
      junos_user:
        name: fortinac
        role: super-user
        encrypted_password: "{{ password }}"
        state: present
