---
- name: Examples of juniper_junos_ping
  hosts: junos-all
  gather_facts: no

  vars:
    connection_settings:
      host: "{{ ansible_host }}"
      port: 22
      timeout: 180


  tasks:
    - name: Ping 10.0.0.1 with default parameters. Fails if any packets lost.
      junos_ping:
        dest: 10.0.0.1