---
- name: Examples of juniper_junos_ping
  hosts: Junos_Test
  gather_facts: no

  vars:
    ansible_command_timeout: 60
    connection_settings:
      host: "{{ ansible_host }}"
      port: 22
      timeout: 180


  tasks:
    - name: Ping 10.190.0.2 with default parameters. Fails if any packets lost.
      junos_ping:
        dest: 10.190.0.2
