---
- name: irb change
  hosts: Junos_all
  connection: local
  gather_facts: no
  roles:
    - Juniper.junos
      
  tasks:
    - name: Append .foo to the hostname using private config mode.
      juniper_junos_config:
        load: 'replace'
        lines:        
          - 'delete protocols pim rp static address 192.168.8.5'        
          - 'set protocols pim rp static address 100.100.80.5'         
      register: response
    - name: Print the config changes.
      debug:
        var: response.diff_lines
