---
- name: irb change
  hosts: Junos_all
  connection: local
  gather_facts: no
  roles:
    - Juniper.junos
      
  tasks:
    - name: Append .foo to the hostname using private config mode.
      juniper_junos_config:
        load: 'replace'
        lines:        
          - 'replace pattern XIRRUS with MIST'
