---
- name: cli command
  hosts: Junos_all
  gather_facts: no

  vars: 
    ansible_connection: network_cli

  tasks:
    - name: show command
      cli_command:
        command:
            - 'replace pattern 192.168.8.5 with 100.10.100.80'
