---
- name: irb change
  hosts: Junos_all
  connection: local
  gather_facts: no
  roles:
    - Juniper.junos
      
  tasks:
    - name: Append .foo to the hostname using private config mode.
      juniper_junos_config:
        load: 'replace'
        lines:        
          - 'delete protocols pim rp static address {{ static1 }}'
          - 'delete protocols pim rp static address {{ static2 }}'           
          - 'set protocols pim rp static address {{ new1 }}' 
          - 'set protocols pim rp static address {{ new2 }}' 
