---
- name: Retrieve Junos OS version
  hosts: Junos_all
  gather_facts: no

  vars:
    ansible_connection: netconf
    ansible_command_timeout: 60


  tasks:
    - name: Retrieve Junos OS version
      junos_command:
        commands: show version
