---
- name: show 
  hosts: Junos_all
  gather_facts: no

  vars:
    ansible_connection: netconf
    ansible_command_timeout: 60


  tasks:
    - name: Show lldp neighbors
      junos_command:
        commands: show lldp neighbors
