---
- name: Retrieve Junos OS version
  hosts: junos-all
  gather_facts: no

  vars:
    #ansible_connection: netconf
    ansible_command_timeout: 60


  tasks:
    - name: Retrieve Junos OS version
      junos_command:
        commands: show version
      when: ansible_network_os == 'junos'

    - name: Print Version
      debug:
        var: stdout_lines[0]
        
- name: Display all variables/facts known for a host
  debug:
    var: hostvars[inventory_hostname]
    verbosity: 4
