---
- name: Examples of juniper_junos_software
  hosts: Junos_all
  connection: local
  gather_facts: no
  roles:
    - Juniper.junos

  tasks:
    - name: Execute a basic Junos software upgrade.
      juniper_junos_software:
        local_package: "tftproot/junos-arm-32-20.2R1-S2.1.tgz"
        force_host: yes
      register: response
    - name: Print the complete response.
      debug:
        var: response
