---
- name: Mist
  hosts: Junos_Test
  roles:
    - Juniper.junos 
  connection: local
  gather_facts: no
 
         
   tasks: 
   - name: collect interface information using rpc
     junos_rpc:
        rpc: get-interface-information
        args:
          interface-range: XIRRUS-WAP
          media: true
