---
- name: Install Junos OS - EX3400
  hosts: Junos_all
  roles:
    - Juniper.junos 
  connection: netconf
  gather_facts: no
  

  tasks:

  - name: run multiple commands and evaluate the output
    juniper_junos_rpc:
     rpcs:
          - "set-protocols-pim-rp-static-address-192.168.8.5"
