---
- name: Test
  hosts: Junos_all
  gather_facts: no

  vars:
    ansible_connection: netconf
    ansible_command_timeout: 60


  tasks: 
    - name: Test 
      junos_command:
        commands: 
          - set protocols pim rp static address 192.168.8.5
