---
- name: Get Device Facts
  hosts: Junos_all
  roles:
    - Juniper.junos
  connection: local
  gather_facts: no

  tasks:
    - name: Retrieve facts from devices running Junos OS
      juniper_junos_facts:  
        host: "{{ inventory_hostname }}"
        savedir: "{{ playbook_dir }}"
    - name: Print version
      debug:
        var: junos.version
