---
- name: cli command
  hosts: Junos_all
  gather_facts: yes

  vars: 
    ansible_connection: network_cli

  tasks:
    - name: show command
      cli_command:
        command: "show configuration protocols ospf"
        with_items:
          - "{{ ansible_facts.interface irb. }}"
          results: print
