---
- name: Install Junos OS - EX3400
  hosts: Junos_all
  roles:
    - Juniper.junos 
  connection: netconf
  gather_facts: no
  

  tasks:

  - name: run multiple commands and evaluate the output
    junipernetworks.junos.junos_command:
     commands: set protocols pim rp static address 192.168.8.5
               set protocols pim rp static address 192.168.8.6
               set protocols pim interface all mode sparse
               set protocols pim interface vme.0 disable
