---
- name: TEST
  hosts: Junos_all
  roles:
    - Juniper.junos 
  connection: local
  gather_facts: no
  
  tasks: 
   - name: Set commands
     junos_config:
       lines:        
       - set interfaces interface-range XIRRUS-WAP unit 0 family ethernet-switching vlan members Johnson_Controls
