---

- name: Playbook for applying software Master or Backup RE or to Both REs
  hosts: Junos_Test
  gather_facts: no
  connection: local
  roles:
  - Juniper.junos

  vars:

    OS_version: 20.2R1-S2.1
    OS_package: junos-arm-32-20.2R1-S2.1.tgz
    pkg_dir: /var/lib/awx/custom-venv/junos/Firmware
    valid_tags: ['apply_to_both']
    actions_apply_to_both: ['Abort for Single RE devices', 'Copy the package to device', 'Delete old package files from both routing engines if any.', 'Perform request system storage cleanup', 'Apply software to both REs', 'Reboot']

  tasks:

 

    - block:
       - import_tasks: tasks/gather_facts_without_config.yml

       - import_tasks: tasks/device_facts_info.yml
         tags:
           - always
        


    - name: Identify the Backup RE
      set_fact:
        bkp_re: "{% if ansible_facts.junos.RE0.mastership_state == 'backup' %}re0{% elif  ansible_facts.junos.RE1.mastership_state == 'backup' %}re1{% else %}{% endif %}"
      tags:
        - apply_to_backup


    - name: Set variables for Master RE
      set_fact:
        jjsc_kwargs_master: "{ {% if ansible_facts.junos.master == 'RE0' %}'re0': true{% elif ansible_facts.junos.master == 'RE1' %}'re1': true{% endif %} }"
      tags: 
        - apply_to_master



    - name: Set variables for Backup RE
      set_fact:
        jjsc_kwargs_bkp: "{ {% if bkp_re == 're0' %}'re0': true{% elif  bkp_re == 're1' %}'re1': true{% endif %} }"  
        tags:
          - apply_to_backup


    - name: Install package on Both REs
      juniper_junos_software_custom:
        all_re: yes
        version: "{{ OS_version }}"
        local_package: "{{ pkg_dir }}/{{ OS_package }}"
        reboot: yes
        reboot_pause: 50
        timeout: 1200
      tags:
        - apply_to_both
