---
- name: LAG
  hosts: Junos_all
  roles:
    - Juniper.junos 
  connection: local
  gather_facts: no
  
  tasks: 
   - name: load configure lines into device
     junos_config:
       lines:        
       - set interfaces ae10 unit 0 family ethernet-switching
       - set interfaces ae10 unit 0 family ethernet-switching storm-control default
       - set interfaces ae10 aggregated-ether-options lacp active         
       - set interfaces ae10 mtu 9100
       - set interfaces et-0/0/24 ether-options 802.3ad ae1
       - set interfaces et-0/0/25 ether-options 802.3ad ae1
       - set protocols rstp interface ae10 disable
       - set protocols vstp interface ae10 disable
        
