---
- name: OSPF/Vlan change
  hosts: Junos_all
  roles:
    - Juniper.junos 
  connection: local
  gather_facts: no
  
  tasks: 
   - name: load configure lines into device
     junos_config:
       lines:
        - set interfaces ae1 unit 0 family ethernet-switching interface mode trunk
        - set interfaces ae1 unit 0 family ethernet-switching vlan member all       
