---
- name: irb change
  hosts: Junos_all
  connection: local
  gather_facts: no
  roles:
    - Juniper.junos
      
  tasks:
    - name: Append .foo to the hostname using private config mode.
      juniper_junos_config:
        load: 'replace'
        lines:
          - 'set protocols ospf area 0.0.0.0 interface irb mtu 1500'        
          - 'set interfaces {{ irb }} family inet address {{ IP }}'
          - 'delete interfaces {{ irb }} family inet address {{ old }}'          
      register: response
    - name: Print the config changes.
      debug:
        var: response.diff_lines
