---
- name: irb change
  hosts: Junos_all
  roles:
    - Juniper.junos 
  connection: local
  gather_facts: no
  
  
  tasks: 
   - name: load configure lines into device
     junos_config:
        lines:
         - "replace pattern {{ old }} with {{ IP }}"
  #       - "set interfaces {{ irb }} family inet address {{ IP }}"

