---
- name: irb change
  hosts: Junos_all
  roles:
    - Juniper.junos 
  connection: netconf
  gather_facts: no
  
  
  tasks: 
   - name: load configure lines into device
     juniper_junos_command:
        commands:
         - "delete interfaces {{ irb }} family inet address {{ old }}"
         - "set interfaces {{ irb }} family inet address {{ IP }}"

