---
- name: irb change
  hosts: Junos_all
  roles:
    - Juniper.junos 
  connection: local
  gather_facts: no
  
  tasks: 
   - name: load configure lines into device
     junos_config:
       lines:
        - delete interfaces {{ irb }} family inet address 100.100.100.66/30
       lines: 
        - set interfaces {{ irb }} family inet address {{ IP }}
