---
- name: irb change
  hosts: Junos_all
  roles:
    - Juniper.junos 
  connection: local
  gather_facts: no
  
  tasks: 
   - name: load configure lines into device
     junos_config:
       update: replace 
          - "replace pattern Test with test12 | match {{ irb }}"
