---
- name: irb change
  hosts: Junos_all
  connection: network_cli
  gather_facts: yes
  
  
  tasks: 
   - name: load configure lines into device
     junos_config:
        lines:
        - set interfaces {{ irb }} family inet {{ IP }}
        - delete interfaces {{ irb }} family inet {{ old }}

        

