---
- name: irb change
  hosts: Junos_all
  connection: local
  gather_facts: no
  roles:
    - Juniper.junos
  tasks:
    - name: Append .foo to the hostname using private config mode.
      juniper_junos_config:
        load: 'set'
        lines:
          - 'set interfaces irb unit 4444 family inet address 69.69.69.69/29'
      
        load: 'replace'
        lines:
          - 'set interfaces {{ irb }} family inet address {{ IP }}'
          - 'delete interfaces {{ irb }} family inet address {{ old }}'          
         
      register: response
    - name: Print the config changes.
      debug:
        var: response.diff_lines
