---
- name: Install Junos OS - EX4600
  hosts: Junos_Test
  roles:
    - Juniper.junos 
  connection: local
  gather_facts: no
  
  vars:
    OS_version: "17.3R3-S3.3"
    OS_package: "jinstall-host-ex-4600-17.3R3-S3.3-signed.tgz"
    pkg_dir: "/var/lib/awx/custom-venv/junos/Firmware"
    install_timeout: 2000
    checksum_timeout: 420

  tasks:

    - name: Install Junos OS package
      juniper_junos_software:
        version: "{{ OS_version }}"
        local_package: "{{ pkg_dir }}/{{ OS_package }}"
        kwargs:
          unlink: yes
        reboot: yes
