---
- name: Install Junos OS - EX4600
  hosts: Junos_all
  roles:
    - Juniper.junos 
  connection: local
  gather_facts: no
  
  vars:
    OS_version: "18.1R3-S3.8"
    OS_package: "junos-arm-32-18.1R3-S3.8.tgz"
    pkg_dir: "/var/lib/awx/custom-venv/junos/Firmware"
    install_timeout: 2000
    checksum_timeout: 420

  tasks:

    - name: Install Junos OS package
      juniper_junos_software:
        version: "{{ OS_version }}"
        local_package: "{{ pkg_dir }}/{{ OS_package }}"
        kwargs:
          unlink: yes
        reboot: yes
