---
- name: Install Junos OS - EX3400
  hosts: Junos_all
  roles:
    - Juniper.junos 
  connection: local
  gather_facts: no
  
  tasks:

    - name: Install Junos OS package
      juniper_junos_software:
        version: "20.2R1-S2.1"
        local_package: "/var/lib/awx/custom-venv/junos/Firmware/junos-arm-32-20.2R1-S2.1.tgz"
        force_host: yes
        kwargs:
          unlink: yes
          reboot: yes
        #nssu: yes
        install_timeout: 2000
        checksum_timeout: 420
        wait_time: 3600
