
---
- name: Not Enough Space Error - EX3400
  hosts: Junos_all
  connection: local
  gather_facts: no
  roles:
    - Juniper.junos

  tasks:
   - name: Install OS package
     juniper_junos_software:
       local_package: "/var/lib/awx/custom-venv/junos/Firmware/os-package.tgz"
       cleanfs: false
       reboot: no
       no_copy: yes
     register: response  
   - name: Print the complete response.
     debug:
       var: response
