---
- name: upgrade junos
  hosts: Junos_Test
  connection: local
  gather_facts: no

  tasks:
  - name: install local package on remote device and reboot the device
    junos_package:
     src: /var/lib/awx/custom-venv/junos/Firmware/junos-arm-32-20.2R1-S2.1.tgz
     force_host: yes
     reboot: true
     provider: netconf
     version: 20.2R1-S2.1
