---
- name: Install Junos OS - EX3400
  hosts: Junos_Test
  connection: netconf
  gather_facts: no
  
  vars:
    OS_version: 20.2R1-S2.1
    OS_package: junos-arm-32-20.2R1-S2.1.tgz
    pkg_dir: /var/lib/awx/custom-venv/junos/Firmware

  tasks:

    - name: Install Junos OS package
      junipernetworks.junos.junos_package:
        version: "{{ OS_version }}"
        src: "{{ pkg_dir }}/{{ OS_package }}"
        force_host: yes
        reboot: true
        validate: no
      register: sw
      notify:
      - wait_reboot

    - name: Print response
      debug:
        var: response

