---
- name: Install Junos OS - EX3400
  hosts: AnsibleTest_Vc
  connection: netconf
  gather_facts: no
  
  tasks:

    - name: install local package on remote device
      junipernetworks.junos.junos_package:
        src: /var/lib/awx/custom-venv/junos/Firmware/junos-arm-32-20.2R1-S2.1.tgz
        force_host: yes
        reboot: yes
