---
- name: Not Enough Space Error
  hosts: Junos_all
  connection: local
  gather_facts: no
  roles:
    - Juniper.junos

  tasks:
    - name: Not Enough Space Error
      juniper_junos_software:
        local_package: "/var/lib/awx/custom-venv/junos/Firmware/os-package.tgz"
      register: response
    - name: Print the complete response.
      debug:
        var: response
