---
- name: juniper_junos_software
  hosts: Junos_Test
  connection: local
  gather_facts: no
  roles:
    - Juniper.junos

  tasks:
    - name: Execute a basic Junos software upgrade.
      juniper_junos_software:
        local_package: "/tftproot/Firmware/junos-arm-32-20.2R1-S2.1.tgz"
        force_host: yes
        nssu: yes
        no_copy: yes
        kwargs:
          unlink: yes
        reboot: yes
      register: response
    - name: Print the complete response.
      debug:
        var: response
