---
- name: Install Junos OS - EX3400
  hosts: Junos_Test
  roles:
    - Juniper.junos 
  connection: netconf
  gather_facts: no
  
  vars:
    OS_version: 20.2R1-S2.1
    OS_package: junos-arm-32-20.2R1-S2.1.tgz
    netconf_port: 830
    wait_time: 3600
    install_timeout: 2000
    checksum_timeout: 420

  tasks:
    - name: Checking NETCONF connectivity
      wait_for: 
        host: "{{ ansible_host }}" 
        port: "{{ netconf_port }}"
        timeout: 20

    - name: Install Junos OS package
      juniper_junos_software:
        version: "{{ OS_version }}"
        remote_package: /mfs/junos-arm-32-20.2R1-S2.1.tgz
        kwargs: 
          unlink: true
        no_copy: yes
        force_host: yes
        reboot: true
        validate: no
      register: sw
      notify:
      - wait_reboot

    - name: Print response
      debug:
        var: response

  handlers:
    - name: wait_reboot
      wait_for: 
        host: "{{ ansible_host }}"
        port: "{{ netconf_port }}"
        timeout: "{{ wait_time }}"
      when: not sw.check_mode
