---
- name: Install Junos OS - Not Enough Space error
  hosts: Junos_all
  roles:
    - Juniper.junos 
  connection: local
  gather_facts: no
  
  vars:
    netconf_port: 830
    wait_time: 3600

  tasks:

    - name: Install OS package
      juniper_junos_software:
       local_package: "/var/lib/awx/custom-venv/junos/Firmware/os-package.tgz"
       force_host: yes
       reboot: no
    
    - name: Install Hooks
      juniper_junos_software:
        local_package: "/var/lib/awx/custom-venv/junos/Firmware/package-hooks-ex.tgz"
        force_host: yes
        reboot: no
    
    - name: Install Junos OS package
      juniper_junos_software:
        version: "20.2R1-S2.1"
        local_package: "/var/lib/awx/custom-venv/junos/Firmware/junos-arm-32-20.2R1-S2.1.tgz"
        kwargs: {"no-copy": true,"force": true,"unlink": true}
        reboot: yes
        force_host: yes
      register: sw
      notify:
      - wait_reboot

  handlers:
    - name: wait_reboot
      wait_for: 
        host: "{{ ansible_host }}"
        port: "{{ netconf_port }}"
        timeout: "{{ wait_time }}"
      when: not sw.check_mode
