---
- name: Install Junos OS - EX3400
  hosts: Junos_Test
  roles:
    - Juniper.junos 
  connection: local
  gather_facts: no
  
  vars:
    OS_version: "20.2R1-S2.1"
    OS_package: "junos-arm-32-20.2R1-S2.1.tgz"
    pkg_dir: "/var/lib/awx/custom-venv/junos/Firmware"

  tasks:
    - name: Checking NETCONF connectivity
      wait_for: 
        host: "{{ ansible_host }}" 
        port: "{{ netconf_port }}"
        timeout: 5

    - name: Install OS package
      juniper_junos_software:
       cleanfs: yes
       local_package: "/var/lib/awx/custom-venv/junos/Firmware/os-package.tgz"
       reboot: no
      register: response  
    - name: Print the complete response.
      debug:
       var: response

    - name: Install Hooks
      juniper_junos_software:
        local_package: "/var/lib/awx/custom-venv/junos/Firmware/package-hooks-ex.tgz"
        reboot: no
      register: response
    - name: Print the complete response.
      debug:
       var: response

    - name: Install Junos OS package
      juniper_junos_software:
        validate: no
        force_host: yes
        version: "{{ OS_version }}"
        local_package: "{{ pkg_dir }}/{{ OS_package }}"
        reboot: true
        cleanfs: yes
      register: sw
      notify:
      - wait_reboot

    - name: Print response
      debug:
        var: response

  handlers:
    - name: wait_reboot
      wait_for: 
        host: "{{ inventory_hostname }}"
        port: "{{ netconf_port }}"
        timeout: "{{ wait_time }}"
      when: not sw.check_mode
