---
- name: Get Interfaces in Interface Ranges
  hosts: Junos_Test
  gather_facts: no
  roles:
    - Juniper.junos
  tasks:
    # - name: Get Interfaces in Interface Ranges from config
    #   juniper_junos_command:
    #     formats: text
    #     commands:
    #       - "show configuration interfaces interface-range {{ range | mandatory }}"
    #   register: dirtyInterfaces
    # - name: print dirtyInterfaces.stdout_lines
    #   debug:
    #     var: dirtyInterfaces.stdout_lines
    
    # # example regex_findall('\\b(?:[0-9]{1,3}\\.){3}[0-9]{1,3}\\b')
    # # interface example ge-0/0/1
    # - name: Grab interfaces from dirtyInterfaces
    #   set_fact:
    #     cacheable: false
    #     cleanInterfaces: |
    #       {{
    #         dirtyInterfaces.stdout_lines | 
    #         map('regex_findall', 'ge-(?:[0-9]{1,2}\\/){2}[0-9]') |
    #         list
    #       }}
    # - name: print cleanInterfaces.stdout_lines
    #   debug:
    #     var: cleanInterfaces

    - name: Get junos config
      juniper_junos_facts:
        config_format: json

    - name: print some stuff
      debug:
        msg: |
          "{{
            ansible_facts.junos.config |
            from_json |
            json_query('configuration.interfaces."interface-range[*]"')
          }}"