---
- name: Get Interfaces in Interface Ranges
  hosts: Junos_Test
  gather_facts: no
  roles:
    - Juniper.junos
  tasks:
    - name: Get junos config
      juniper_junos_facts:
        config_format: json

    - name: Grab interfaces of interface ranges
      set_fact:
        cacheable: false
        interfaces: "{{ ansible_facts.junos.config | from_json | json_query(query) | list }}"
      vars:
        query: "configuration.interfaces.\"interface-range\"[?name=='{{ range }}'].member[*].name"

    - name: print some stuff
      debug:
        var: interfaces
