---
- name: Get Interfaces in Interface Ranges
  hosts: Junos_Test
  gather_facts: no
  roles:
    - Juniper.junos
  tasks:
    - name: Get Interfaces in Interface Ranges from config
      juniper_junos_command:
        formats: text
        commands:
          - "show configuration interfaces interface-range {{ range | mandatory }}"
      register: dirtyInterfaces
    - name: print dirtyInterfaces.stdout[0]
      debug:
        var: dirtyInterfaces.stdout[0]
    
    # example regex_findall('\\b(?:[0-9]{1,3}\\.){3}[0-9]{1,3}\\b')
    # interface example ge-0/0/1
    - name: Grab interfaces from dirtyInterfaces
      set_fact:
        cacheable: false
        cleanInterfaces: |
          {{
            dirtyInterfaces.stdout_lines | 
            map('regex_findall', '\\bge-[0-9][/][0-9][/][0-9]\\b') |
            list 
          }}
    - name: print cleanInterfaces.stdout_lines
      debug:
        var: cleanInterfaces
