---
- name: Get Interfaces in Interface Ranges
  hosts: Junos_Test 
  connection: local
  gather_facts: no
  tasks:   
    - name: Get Interfaces in Interface Ranges from config
      junos_command: 
        commands:
          - "show configuration interfaces interface-range {{ range }} | match \"member ge-*\""
      register: dirtyInterfaces
    - name: Parse through and remove member
      debug:
        var: dirtyInterfaces