---
- name: Convert Interface Ranges to Interfaces
  hosts: Junos_Test
  gather_facts: no
  roles:
    - Juniper.junos
  vars:
  tasks:
    - name: Get junos facts
      juniper_junos_facts:
        config_format: json

    - name: Grab interfaces of interface ranges
      set_fact:
        cacheable: false
        interfaces: "{{ ansible_facts.junos.config | from_json | json_query(query) | flatten }}"
      vars:
        query: "configuration.interfaces.\"interface-range\"[?name=='{{ range | mandatory }}'].member[*].name"

    - name: print some stuff
      debug:
        var: interfaces

    - name: Load a configuration from a Jinja2 template and commit
      juniper_junos_config:
        load: "merge"
        template: "./{{ range | lower }}.j2"
        format: "text"
        var:
          interfaces: "{{ interfaces }}"
      register: response
      
    - name: Print Response
      debug:
        var: response