---
- name: Load and commit configuration 
  hosts: Junos_Test
  roles:
    - Juniper.junos
  connection: local
  gather_facts: no

  tasks:
    - name: Load configuration from a local file and commit
      juniper_junos_config:
        load: "override"
        src: /var/lib/awx/custom-venv/junos/configuration/text/WELCOME_CENTER_OFFICES.txt
      register: response
    - name: Print the response
      debug:
        var: response
