---
- name: Gather Configuration
  hosts: Cisco_all
  gather_facts: no
  connection: network_cli
  tasks:

   - name: create configuration directory
     file:
       path: "/var/lib/awx/custom-venv/junos/configuration"
       state: directory


   - name: create configuration subdirectories
     file:
       path: "/var/lib/awx/custom-venv/junos/configuration/{{ item }}"
       state: directory
     with_items:
       - text
  

   - name: Collect configuration in text format from devices
     cisco.ios.ios_facts:
        gather_subset:
          - config
     config_format: text
     register: "result_text"

   - name: copy collected configuration in configuration/text directory
     copy: 
     content: "{{ result_text.ansible_facts.ansible_net_config }}" 
     dest: "/var/lib/awx/custom-venv/junos/configuration/text/{{ inventory_hostname }}.conf"
