---
- name: Gather Configuration
  hosts: Cisco_all
  roles:
    - cisco.ios
  gather_facts: no
  connection: local
  tasks:

  - name: Gather all legacy facts
    cisco.ios.ios_facts:
      gather_subset: all
      config_format: text
    register: "result_text"

  - name: copy collected configuration in configuration/text directory
    copy: 
       content: "{{ result_text.ansible_facts.ansible_net_config }}" 
       dest: "/var/lib/awx/custom-venv/junos/configuration/text/{{ inventory_hostname }}.conf"
