---
- name: Change interface to access 
  hosts: Junos_all
  connection: local
  gather_facts: no
  
  tasks:
  
    - name: Set VLAN access and trunking
      junipernetworks.junos.junos_config:
        lines:
          - delete interface {{ irb }} family inet address {{ old }}
