---
- name: Install Junos OS - EX3400
  hosts: Junos_all
  roles:
    - Juniper.junos
  connection: netconf
  gather_facts: no
 
  tasks: 
  
   - name: load configure lines into device
     junos_config:
       lines:
        - set system authentication-order password 
        - set system authentication-order radius
        - set system radius-server 10.0.6.45 port 1645
       comment: update config
