---
- name: Install Junos OS - EX3400
  hosts: Junos_all
  roles:
    - Juniper.junos 
  connection: local
  gather_facts: no
 
  tasks: 
  
   - name: load configure lines into device
     junos_config:
       lines:
        - set system authentication-order password 
        - set system authentication-order radius
        - set system radius-server 10.0.6.45 port 1645
        - set system radius-server 10.0.6.45 secret "$9$fTQ36/Ctp0xNgJGUHk9ApBIceKMXx-cS-wYgJZUjiHqfz36CpBF3Cu"
        - set system radius-server 10.0.6.45 source-address "{{ ansible_host }}"
       comment: update config
